export const CONFIG = Object.freeze({
  PORT: `PORT`,
  ENVIROMENT: `ENVIROMENT`,
  SSL_CRT_FILE: `SSL_CRT_FILE`,
  SSL_KEY_FILE: `SSL_KEY_FILE`,
  REDIS_DB: "REDIS_DB",
  REDIS_PASSWORD: "REDIS_PASSWORD",
  REDIS_HOST: "REDIS_HOST",
  REDIS_PORT: "REDIS_PORT",

  MONGO_SRV: "MONGO_SRV",
  JWT_SECRET: "JWT_SECRET",

  NODEMAILER_EMAIL: `NODEMAILER_EMAIL`,
  NODEMAILER_PASSWORD: `NODEMAILER_PASSWORD`,

  FONTEND_URL: `FONTEND_URL`,
});
